version: "3.8"

services:
  truffle:
    build: .
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    ports:
      - 8545:8545
    command: ganache --server.host 0.0.0.0 --wallet.mnemonic "bleak capital wish that develop impulse regular magnet verb spatial west fever"
